scratch: scratch.c
	clang -Wall -o bin/scratch scratch.c

all: hello.c race.c retval.c simple.c tid.c
	clang -Wall -o bin/hello hello.c
	clang -Wall -o bin/race race.c
	clang -Wall -o bin/retval retval.c
	clang -Wall -o bin/simple simple.c
	clang -Wall -o bin/tid tid.c

